export default {
  face: [
    {
      img: './img/1/7.png',
      title: '这是洗脸用的吗',
      background: '#d6ecfa',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/1/8.png',
      title: '为你编程研制',
      background: '#fab1ce',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/1/2.png',
      title: '女装首选',
      background: '#f6ea8c',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/1/1.png',
      title: '为你编程特制',
      background: '#566270',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/1/2.png',
      title: '女装必备',
      background: '#E0E3DA',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/1/3.png',
      title: '双十一必抢',
      background: '#A593E0',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/1/4.png',
      title: '让你后悔出生为男人',
      background: '#D499B9',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/1/5.png',
      title: '不简单的',
      background: '#4F86C6',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/1/6.png',
      title: '炸裂神器',
      background: '#41D3BD',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
  ],
  lipstick: [
    {
      img: './img/2/6.png',
      title: '炸裂神器',
      background: '#41D3BD',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/2/10.png',
      title: '女装首选',
      background: '#f6ea8c',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/2/4.png',
      title: '为你编程研制',
      background: '#fab1ce',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/2/7.png',
      title: '这是洗脸用的吗',
      background: '#d6ecfa',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/2/2.png',
      title: '女装必备',
      background: '#E0E3DA',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/2/3.png',
      title: '双十一必抢',
      background: '#A593E0',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/2/1.png',
      title: '为你编程特制',
      background: '#566270',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/2/4.png',
      title: '让你后悔出生为男人',
      background: '#D499B9',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/2/5.png',
      title: '不简单的',
      background: '#4F86C6',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/2/9.png',
      title: '炸裂神器',
      background: '#41D3BD',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
  ],
  mascara: [
    {
      img: './img/3/1.png',
      title: '为你编程特制',
      background: '#566270',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/3/2.png',
      title: '女装必备',
      background: '#E0E3DA',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/3/3.png',
      title: '双十一必抢',
      background: '#A593E0',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/3/4.png',
      title: '让你后悔出生为男人',
      background: '#D499B9',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/3/5.png',
      title: '不简单的',
      background: '#4F86C6',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
    {
      img: './img/3/6.png',
      title: '炸裂神器',
      background: '#41D3BD',
      description: '抹足一百八十天，抹出美丽抹出鲜',
      price: 200,
    },
  ],
};
